namespace NierReincarnation.Core.Dark.View.UserInterface.Text
{
    public static partial class UserInterfaceTextKey
    {
        public static class Enhance
        {
            public static readonly string kEnhance = "ui.Outgame.Enhance.Enhance"; // 0x0
            public static readonly string kLimitBreak = "ui.Outgame.Enhance.Breakthrough"; // 0x8
            public static readonly string kAscended = "ui.Outgame.Enhance.Breakthrough.Ascended"; // 0x10
            public static readonly string kEvolution = "ui.Outgame.Enhance.Evolution"; // 0x18
            public static readonly string kEndEvolution = "ui.Outgame.Enhance.EndEvolution"; // 0x20
            public static readonly string kAbility = "ui.Outgame.Enhance.Ability"; // 0x28
            public static readonly string kAwaken = "ui.Outgame.Enhance.Awaken"; // 0x30
            public static readonly string kWeaponAwaken = "ui.Outgame.Enhance.WeaponAwaken"; // 0x38
            public static readonly string kEnhanceConfirm = "ui.Outgame.Enhance.EnhanceConfirm"; // 0x40
            public static readonly string kEnhanceSkillConfirm = "ui.Outgame.Enhance.EnhanceSkillConfirm"; // 0x48
            public static readonly string kLimitBreakConfirm = "ui.Outgame.Enhance.BreakthroughConfirm"; // 0x50
            public static readonly string kLimitBreakConfirmCountOver = "ui.Outgame.Enhance.BreakthroughConfirm.CountOver"; // 0x58
            public static readonly string kEvolutionConfirm = "ui.Outgame.Enhance.EvolutionConfirm"; // 0x60
            public static readonly string kAwakenConfirmTitle = "ui.Outgame.Enhance.AwakenConfirm.Title"; // 0x68
            public static readonly string kAwakenStatusDetailTitle = "ui.Outgame.Enhance.AwakenStatusDetail.Title"; // 0x70
            public static readonly string kWeaponAwakenConfirm = "ui.Outgame.Enhance.WeaponAwakenConfirm"; // 0x78
            public static readonly string kSuccess = "ui.Outgame.Enhance.Success"; // 0x80
            public static readonly string kFailed = "ui.Outgame.Enhance.Failed"; // 0x88
            public static readonly string kReleaseAbiltiy = "ui.Outgame.Enhance.ReleaseAbility"; // 0x90
            public static readonly string kReleaseBlessAbiltiy = "ui.Outgame.Enhance.ReleaseBlessAbility"; // 0x98
            public static readonly string kReleaseAwakenAbility = "ui.Outgame.Enhance.Awaken.ReleaseAbility"; // 0xA0
            public static readonly string kReleaseAwakenThought = "ui.Outgame.Enhance.Awaken.ReleaseThought"; // 0xA8
            public static readonly string kReinforcedSkill = "ui.Outgame.Enhance.Reinforced.Skill"; // 0xB0
            public static readonly string kReinforcedAbility = "ui.Outgame.Enhance.Reinforced.Ability"; // 0xB8
            public static readonly string kLockAwaken = "ui.Outgame.Enhance.Awaken.Lock"; // 0xC0
            public static readonly string kAwakenStatusUp = "ui.Outgame.Enhance.Awaken.StatusUp"; // 0xC8
            public static readonly string kErrorNoEvolution = "ui.Outgame.Enhance.Error.NoEvolution"; // 0xD0
            public static readonly string kErrorMaxEvolution = "ui.Outgame.Enhance.Error.MaxEvolution"; // 0xD8
            public static readonly string kErrorNoWeaponAwaken = "ui.Outgame.Enhance.Error.NoWeaponAwaken"; // 0xE0
            public static readonly string kErrorMaxWeaponAwaken = "ui.Outgame.Enhance.Error.MaxWeaponAwaken"; // 0xE8
            public static readonly string kErrorNeedEvolutionWeaponAwaken = "ui.Outgame.Enhance.Error.NeedEvolutionWeaponAwaken"; // 0xF0
            public static readonly string kErrorMaxSkillEnhance = "ui.Outgame.Enhance.Error.MaxSkillEnhance"; // 0xF8
            public static readonly string kErrorMaxSelected = "ui.Outgame.Enhance.Error.MaxSelected"; // 0x100
            public static readonly string kErrorSelectMaterial = "ui.Outgame.Enhance.Error.SelectMaterial"; // 0x108
            public static readonly string kErrorLackMaterial = "ui.Outgame.Enhance.Error.LackMaterial"; // 0x110
            public static readonly string kErrorSkillNoSelect = "ui.Outgame.Enhance.Error.SkillNoSelect"; // 0x118
            public static readonly string kErrorSkillLocked = "ui.Outgame.Enhance.Error.SkillLocked"; // 0x120
            public static readonly string kErrorIsOrganized = "ui.Outgame.Enhance.Error.IsOrganized"; // 0x128
            public static readonly string kErrorIsProtected = "ui.Outgame.Enhance.Error.IsProtected"; // 0x130
            public static readonly string kErrorIsRestrictDiscard = "ui.Outgame.Enhance.Error.IsRestrictDiscard"; // 0x138
            public static readonly string kAlertMaxLimitBreak = "ui.Outgame.Enhance.Alert.MaxLimitBreak"; // 0x140
            public static readonly string kAlertMaxAwaken = "ui.Outgame.Enhance.Alert.MaxAwaken"; // 0x148
            public static readonly string kAlertNoMaterial = "ui.Outgame.Enhance.Alert.NoMaterial"; // 0x150
            public static readonly string kAlertNoRecommendMaterial = "ui.Outgame.Enhance.Alert.NoRecommendMaterial"; // 0x158
            public static readonly string kAlertNoRecommendWeapon = "ui.Outgame.Enhance.NoRecommendWeapon"; // 0x160
            public static readonly string kAlertMaxLevel = "ui.Outgame.Enhance.Alert.MaxLevel"; // 0x168
            public static readonly string kAlertNeedLevel = "ui.Outgame.Enhance.Alert.NeedLevel"; // 0x170
            public static readonly string kAlertRarityWeapon = "ui.Outgame.Enhance.Alert.Rarity.Weapon"; // 0x178
            public static readonly string kAlertEnhancedWeapon = "ui.Outgame.Enhance.Alert.Enhanced.Weapon"; // 0x180
            public static readonly string kAlertLimitBreakWeapon = "ui.Outgame.Enhance.Alert.LimitBreak.Weapon"; // 0x188
            public static readonly string kAlertRarityItem = "ui.Outgame.Enhance.Alert.Rarity.Item"; // 0x190
            public static readonly string kAlertSameWeapon = "ui.Outgame.Enhance.Alert.Same.Weapon"; // 0x198
            public static readonly string kNextLevel = "ui.Outgame.Enhance.NextLevel"; // 0x1A0
            public static readonly string kGreatSuccess = "ui.Outgame.Enhance.GreatSuccess"; // 0x1A8
            public static readonly string kDirectionTitleSkillLevelUp = "ui.Outgame.Enhance.Direction.Title.SkillLevelUp"; // 0x1B0
            public static readonly string kAutoOrganizationTitle = "ui.Outgame.Enhance.AutoOrganizationTitle"; // 0x1B8
            public static readonly string kLackGold = "ui.Outgame.Enhance.LackGold"; // 0x1C0
            public static readonly string kSuccessRate = "ui.Outgame.Enhance.SuccessRate"; // 0x1C8
            public static readonly string kMemoryMaxLevelConfirm = "ui.Outgame.Enhance.Memory.MaxLevelConfirm"; // 0x1D0
            public static readonly string kMaxEnhance = "ui.Outgame.Enhance.MaxEnhance"; // 0x1D8
            public static readonly string kMaxEnhanceStop = "ui.Outgame.Enhance.MaxEnhanceStop"; // 0x1E0
            public static readonly string kConsumeWeapon = "ui.Outgame.Enhance.Consume.Weapon"; // 0x1E8
            public static readonly string kConsumeItem = "ui.Outgame.Enhance.ConsumeItem"; // 0x1F0
            public static readonly string kLevelLimit = "ui.Outgame.Enhance.Memory.ReleaseSubBonus"; // 0x1F8
            public static readonly string kMemoryMainBonus = "ui.Outgame.Enhance.Memory.MainBonus"; // 0x200
            public static readonly string kMemorySubBonus = "ui.Outgame.Enhance.Memory.SubBonus"; // 0x208
            public static readonly string kMemoryReleaseSubBonus = "ui.Outgame.Enhance.Memory.ReleaseSubBonus"; // 0x210
            public static readonly string kEvolutionOrderStage = "ui.Outgame.Enhance.Evolution.Order.Stage"; // 0x218
            public static readonly string kEvolutionOrderStageFinal = "ui.Outgame.Enhance.Evolution.Order.Stage.Final"; // 0x220
            public static readonly string kSurplusTitle = "ui.Outgame.Enhance.Surplus.Title"; // 0x228
            public static readonly string kSurplusItem = "ui.Outgame.Enhance.Surplus.Item"; // 0x230
            public static readonly string kSurplusDescription = "ui.Outgame.Enhance.Surplus.Description"; // 0x238
            public static readonly string kSkillItem = "ui.Outgame.Enhance.SkillItemCheck"; // 0x240
            public static readonly string kSkillItemSSRCaution = "ui.Outgame.Enhance.SkillItemSSRCaution"; // 0x248
            private const string kCharacterBoard = "ui.Outgame.Enhance.CharacterBoard."; // 0x250
            public static readonly string kCharacterBoardProgress = kCharacterBoard + "Progress"; // 0x258
            public static readonly string kCharacterBoardReleaseCount = kCharacterBoard + "Release.Count"; // 0x260
            public static readonly string kCharacterBoardReleaseConfirmation = kCharacterBoard + "ReleaseConfirmation"; // 0x268
            public static readonly string kCharacterBoardReleaseInformation = kCharacterBoard + "Release.Info"; // 0x270
            public static readonly string kCharacterBoardRelease = kCharacterBoard + "Release"; // 0x278
            public static readonly string kCharacterBoardBaseStatus = kCharacterBoard + "Status"; // 0x280
            public static readonly string kCharacterBoardAllBoard = kCharacterBoard + "AllBoard"; // 0x288
            public static readonly string kCharacterBoardAbilityLevel = kCharacterBoard + "Ability.Lv"; // 0x290
            public static readonly string kCharacterBoardAllCostume = kCharacterBoard + "AllCostume"; // 0x298
            public static readonly string kCharacterBoardNeedCondition = kCharacterBoard + "NeedCondition"; // 0x2A0
            public static readonly string kCharacterBoardDisableChange = kCharacterBoard + "DisableChangeGroup"; // 0x2A8
            public static readonly string kCharacterBoardNeedTutorial = kCharacterBoard + "NeedTutorial"; // 0x2B0
            public static readonly string kCharacterBoardReleaseRank = kCharacterBoard + "ReleaseRank"; // 0x2B8
            public static readonly string kCharacterBoardNeedReleaseParentPanel = kCharacterBoard + "NeedReleaseParentPanel"; // 0x2C0
            public static readonly string kCharacterBoardProgressTitle = kCharacterBoard + "Progress.Title"; // 0x2C8
            private const string kRebirth = "ui.Outgame.Enhance.Rebirth."; // 0x2D0
            public static readonly string kRebirthTitle = kRebirth + "Title"; // 0x2D8
            public static readonly string kRebirthConfirmation = kRebirth + "Confirmation"; // 0x2E0
            public static readonly string kAlertMaxRebirth = kRebirth + "MaxRebirth"; // 0x2E8
        }
    }
}
