namespace NierReincarnation.Core.Dark.View.UserInterface.Text
{
    public static partial class UserInterfaceTextKey
    {
        public static class Shop
        {
            public static readonly string kShopLabelPromotionSale = "ui.Outgame.Shop.Label.Promotion.Sale"; // 0x0
            public static readonly string kShopLabelPromotionPickup = "ui.Outgame.Shop.Label.Promotion.Pickup"; // 0x8
            public static readonly string kShopLabelPromotionIncrease = "ui.Outgame.Shop.Label.Promotion.Increase"; // 0x10
            public static readonly string kShopSubmitAgeNocheck = "ui.Outgame.Shop.Submit.Age.NoCheck"; // 0x18
            public static readonly string kItemRemainingCount = "ui.Outgame.Shop.Item.RemainingCount"; // 0x20
            public static readonly string kMissionDetailNoLimitTextKey = "ui.Outgame.Shop.Mission.Detail.Nolimit"; // 0x28
            public static readonly string kMissionDetailLimitTextKey = "ui.Outgame.Shop.Mission.Detail.Limit"; // 0x30
            public static readonly string kFundSettlementMethodTextKey = "ui.Outgame.Shop.FundSettlementMethod.Button"; // 0x38
            public static readonly string kSpecifiedCommercialCodeTransactionTextKey = "ui.Outgame.Shop.SpecifiedCommercialCodeTransactionLaw.Title"; // 0x40
            public static readonly string kPurchaseNotificationTextKey = "ui.Outgame.Shop.Purchase.Notification.Title"; // 0x48
            public static readonly string kPurchaseLimitTextKey = "ui.Outgame.Shop.Purchase.Notification.Limit"; // 0x50
            public static readonly string kItemRemainingTimeDay = "ui.Outgame.Shop.Item.RemainingTime.Day"; // 0x58
            public static readonly string kItemRemainingTimeHour = "ui.Outgame.Shop.Item.RemainingTime.Hour"; // 0x60
            public static readonly string kPurchaseGemJump = "ui.Outgame.Shop.Purchase.Gem.Jump"; // 0x68
            public static readonly string kPurchaseShopJump = "ui.Outgame.Shop.Purchase.Shop.Jump"; // 0x70
            public static readonly string kUnitMark = "ui.Outgame.Shop.UnitMark"; // 0x78
            public static readonly string kResetProductConfirmTitle = "ui.Outgame.Shop.ResetProductConfirm.Title"; // 0x80
            public static readonly string kResetProductConfirmMessage = "ui.Outgame.Shop.ResetProductConfirm.Message"; // 0x88
            public static readonly string kPurchaseAdultMessage = "ui.Outgame.Shop.Purchase.Adult.Message"; // 0x90
            public static readonly string kPurchaseMinorsMessage = "ui.Outgame.Shop.Purchase.Minors.Message"; // 0x98
            public static readonly string kPurchaseUnder16Message = "ui.Outgame.Shop.Purchase.Under16.Message"; // 0xA0
            public static readonly string kPurchaseUnder16Count = "ui.Outgame.Shop.Purchase.Under16.Count"; // 0xA8
            public static readonly string kPurchaseMinorsCount = "ui.Outgame.Shop.Purchase.Minors.Count"; // 0xB0
            public static readonly string kSubmitAgeTitleRegister = "ui.Outgame.Shop.Submit.Age.Title.Register"; // 0xB8
            public static readonly string kSubmit = "ui.Outgame.Shop.Submit"; // 0xC0
            public static readonly string kSubmitAgeErrorTitle = "ui.Outgame.Shop.Submit.Age.error.title"; // 0xC8
            public static readonly string kSubmitAgeErrorMessage = "ui.Outgame.Shop.Submit.Age.error.message"; // 0xD0
            public static readonly string kSubmitAgeTitleConfirmation = "ui.Outgame.Shop.Submit.Age.Title.Confirmation"; // 0xD8
            public static readonly string kSubmitConfirmationDone = "ui.Outgame.Shop.Submit.Confirmation.Done"; // 0xE0
            public static readonly string kSubmitAgeTemplate = "ui.Outgame.Shop.Submit.Age.Template"; // 0xE8
            public static readonly string kPurchase = "ui.Outgame.Shop.Purchase"; // 0xF0
            public static readonly string kConfirmation = "ui.Outgame.Shop.Confirmation"; // 0xF8
            public static readonly string kPurchaseDetail = "ui.Outgame.Shop.PurchaseDetail"; // 0x100
            public static readonly string kGem = "ui.Outgame.Shop.Gem"; // 0x108
            public static readonly string kPurchaseDone = "ui.Outgame.Shop.Purchase.Done"; // 0x110
            public static readonly string kConfirmCount = "ui.Outgame.Shop.Confirm.Count"; // 0x118
            public static readonly string kConfirmPurchase = "ui.Outgame.Shop.Confirm.Purchase"; // 0x120
            public static readonly string kExchangeExchange = "ui.Outgame.Shop.Exchange.Exchange"; // 0x128
            public static readonly string kConfirmExchange = "ui.Outgame.Shop.Confirm.Exchange"; // 0x130
            public static readonly string kItem = "ui.Outgame.Shop.Item"; // 0x138
            public static readonly string kSubmitAgeTitle = "ui.Outgame.Shop.Submit.Age.Title"; // 0x140
            public static readonly string kUpdateTimeMessage = "ui.Outgame.Shop.Update.Time.Message"; // 0x148
            public static readonly string kPurchaseErrorTitle = "ui.Outgame.Shop.Purchase.Error.Title"; // 0x150
            public static readonly string kAlertNoSelect = "ui.Outgame.Shop.Alert.NoSelect"; // 0x158
            public static readonly string kAlertNoSelectBuyItem = "ui.Outgame.Shop.Alert.NoSelectBuyItem"; // 0x160
            public static readonly string kAlertLackGold = "ui.Outgame.Shop.Alert.LackGold"; // 0x168
            public static readonly string kItemUpdate = "ui.Outgame.Shop.Item.Update"; // 0x170
            public static readonly string kItemUpdateEnd = "ui.Outgame.Shop.Item.Update.End"; // 0x178
            public static readonly string kSoldOut = "ui.Outgame.Shop.SoldOut"; // 0x180
            public static readonly string kNotEnough = "ui.Outgame.Shop.NotEnough"; // 0x188
            public static readonly string kBuyErrorLimitPossessionCount = "ui.Outgame.Shop.Buy.Error.LimitPossessionCount"; // 0x190
            public static readonly string kExchangeLinkPvp = "ui.Outgame.Shop.Exchange.Link.Pvp"; // 0x198
            public static readonly string kExchangeLinkEvent = "ui.Outgame.Shop.Exchange.Link.Event"; // 0x1A0
            public static readonly string kExchangeLinkGacha = "ui.Outgame.Shop.Exchange.Link.Gacha"; // 0x1A8
            public static readonly string kExchangeLinkBigHunt = "ui.Outgame.Shop.Exchange.Link.BigHunt"; // 0x1B0
            public static readonly string kPremium = "ui.Outgame.Shop.Premium"; // 0x1B8
            public static readonly string kPurchaseErrorUnknown = "ui.Outgame.Shop.Purchase.Error.Unknown"; // 0x1C0
            public static readonly string kPurchaseErrorUnknownGooglePlay = "ui.Outgame.Shop.Purchase.Error.Unknown.GooglePlay"; // 0x1C8
            public static readonly string kPurchaseErrorUnknownAmazonStore = "ui.Outgame.Shop.Purchase.Error.Unknown.AmazonStore"; // 0x1D0
            public static readonly string kPurchaseErrorLimit = "ui.Outgame.Shop.Purchase.Error.Limit"; // 0x1D8
            public static readonly string kPurchaseErrorLimitUnder16 = "ui.Outgame.Shop.Purchase.Error.Limit.Under16"; // 0x1E0
            public static readonly string kPurchaseErrorLimitMinors = "ui.Outgame.Shop.Purchase.Error.Limit.Minors"; // 0x1E8
            public static readonly string kPurchaseErrorRefund = "ui.Outgame.Shop.Purchase.Error.Refund"; // 0x1F0
            public static readonly string kPurchaseErrorRetry = "ui.Outgame.Shop.Purchase.Error.Retry"; // 0x1F8
            public static readonly string kPurchaseErrorCancel = "ui.Outgame.Shop.Purchase.Error.Cancel"; // 0x200
            public static readonly string kUpdateTimeMonth = "ui.Outgame.Shop.Update.Time"; // 0x208
            public static readonly string kUpdateTimeWeek = "ui.Outgame.Shop.Update.ArenaTime"; // 0x210
            public static readonly string kMainItem = "ui.Outgame.Shop.Item.MainItem"; // 0x218
            public static readonly string kBonusItem = "ui.Outgame.Shop.Item.BonusItem"; // 0x220
            public static readonly string kGemItemName = "ui.Outgame.Shop.Gem.ItemName"; // 0x228
            public static readonly string kGemItemGemBreakdown = "ui.Outgame.Shop.Gem.ItemGemBreakdown"; // 0x230
            public static readonly string kGemItemGemBreakdownIncrease = "ui.Outgame.Shop.Gem.ItemGemBreakdown.Increase"; // 0x238
            public static readonly string kItemRemainingTimeTerm = "ui.Outgame.Shop.Item.RemainingTime.Term"; // 0x240
            public static readonly string kExchangeChangeDescriptionPossessionChara = "ui.Outgame.Shop.Exchange.ChangeDescription.PossessionChara.ver2"; // 0x248
            public static readonly string kExchangeChangeDescriptionFirstTime = "ui.Outgame.Shop.Exchange.ChangeDescription.FirstTime"; // 0x250
            public static readonly string kExchangeChangeDescriptionFirstTimeGetMulti = "ui.Outgame.Shop.Exchange.ChangeDescription.FirstTimeGetMulti.ver2"; // 0x258
            public static readonly string kExchangeChangeCautionCostumePossession = "ui.Outgame.Shop.Exchange.ChangeDescription.CautionCostumePossession.ver2"; // 0x260
            public static readonly string kPurchaseWarningInfo = "ui.Outgame.Shop.Purchase.Warning.Information"; // 0x268
            public static readonly string kPurchaseWarningTerm = "ui.Outgame.Shop.Purchase.Warning.Term"; // 0x270
            public static readonly string kPurchaseWarningMonthUpdate = "ui.Outgame.Shop.Purchase.Warning.MonthUpdate"; // 0x278
            public static readonly string kPurchaseWarningMission = "ui.Outgame.Shop.Purchase.Warning.Mission"; // 0x280
            public static readonly string kPurchaseWarningToGift = "ui.Outgame.Shop.Purchase.Warning.ToGift"; // 0x288
            public static readonly string kShopLabelPromotionDailyLimited = "ui.Outgame.Shop.Label.Promotion.DailyLimited"; // 0x290
            public static readonly string kSoldOutLabelDailyLimitedReset = "ui.Outgame.Shop.SoldOut.Label.DailyLimitedReset"; // 0x298
            public static readonly string kItemDailyRemainigCount = "ui.Outgame.Shop.Item.DailyRemainingCount"; // 0x2A0
            public static readonly string kSoldOutLabel = "ui.Outgame.Shop.SoldOut.Label"; // 0x2A8
            public static readonly string kConfirmMaxCount = "ui.Outgame.Shop.Confirm.MaxCount"; // 0x2B0
            public static readonly string kPurchaseWarningMissionPass = "ui.Outgame.Shop.Purchase.Warning.MissionPass"; // 0x2B8
            public static readonly string kExchangeChangeDescriptionPossessionCharaOld = "ui.Outgame.Shop.Exchange.ChangeDescription.PossessionChara"; // 0x2C0
            public static readonly string kExchangeChangeDescriptionFirstTimeGetMultiOld = "ui.Outgame.Shop.Exchange.ChangeDescription.FirstTimeGetMulti"; // 0x2C8
            public static readonly string kExchangeChangeCautionCostumePossessionOld = "ui.Outgame.Shop.Exchange.ChangeDescription.CautionCostumePossession"; // 0x2D0
            public static readonly string kShopName = "shop." + CommonKeyParts.kName; // 0x2D8
        }
    }
}
